### ISSUE TITLE
Unable to get my background image to show on GitHub pages. Help!

### ISSUE THREAD

**Issue by Jennp1987** [Jennp1987/644_final#1]
Hi, I have been trying to correct the path to get my background image to show while hosted on GitHub. I can get it to show when viewing my app from Brackets just not when it's hosted.  My CSS is definitely working but I just can't seem to get my image to show. I've been looking at other threads but nothing seems to make a difference. Any help would be appreciated. 

My CSS...
#backgroundImage {
    padding-top: 3%;
    padding-bottom: 97%;
    background-image: url('https://jennp1987.github.io/644_final/images/pizza_bkground.png');
    background-size: cover;
    background-repeat: no-repeat;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
}
My website repo 
https://github.com/Jennp1987/644_final

**Comment by josereu** [comment]
use ./ before url, that worked for me.

![image](https://user-images.githubusercontent.com/18534354/115317978-017bd580-a13a-11eb-9156-23bb5f7f950d.png)

![image](https://user-images.githubusercontent.com/18534354/115318074-2a9c6600-a13a-11eb-84b5-6c167b57412d.png)
